CREATE TABLE accommodations
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    category   VARCHAR(255)                            NOT NULL,
    condition  VARCHAR(255)                            NOT NULL DEFAULT 'GOOD',
    rented     BOOLEAN                                 NOT NULL DEFAULT FALSE,
    num_rooms  INTEGER                                 NOT NULL,
    host_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_accommodations PRIMARY KEY (id)
);

CREATE TABLE countries
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    continent VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE TABLE hosts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    surname    VARCHAR(255)                            NOT NULL,
    country_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_hosts PRIMARY KEY (id)
);

ALTER TABLE countries
    ADD CONSTRAINT uc_countries_name UNIQUE (name);

ALTER TABLE accommodations
    ADD CONSTRAINT FK_ACCOMMODATIONS_ON_HOST FOREIGN KEY (host_id) REFERENCES hosts (id);

ALTER TABLE hosts
    ADD CONSTRAINT FK_HOSTS_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES countries (id);